# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: lone douglas music
email: intrepid.trevor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lone Douglas Music illuminates poetry into action. We should vocalize those words we absorb, those pictures we imagine, and those dreams we sing in our minds. At Lone Douglas you will find those lines of poems reimagined- in a word reheard. 
# It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
facebook_username: Trevor Tustin
github_username:  codertrev

# Build settings
markdown: kramdown
